[build]
  base    = ""
  publish = "fixtures/dom/build"
  command = "npm build --type=UMD_DEV && cd fixtures/dom/ && npm && npm prestart && npm build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200